language: go

go:
  - 1.12.x

install:
  - go get -t ./...
  - npm install --global web-ext

script:
  - go vet ./...
  - go test ./...
  - go build
  - web-ext lint -s firefox-extension
  - web-ext build -s firefox-extension
